# Generated by Django 3.1.8 on 2021-04-12 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='listings',
            new_name='Listing',
        ),
    ]
