# Generated by Django 3.1.8 on 2021-04-14 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='listing_id',
        ),
    ]
