# Generated by Django 3.1.8 on 2021-04-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20210414_0826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='realtor_email',
        ),
        migrations.AddField(
            model_name='contact',
            name='listing_id',
            field=models.CharField(default='a@b.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='user_email',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
